# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Blog

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodule
      uses: Mushus/checkout-submodule@v1.0.1
      with:
        submodulePath: themes/next
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: node_modules
        key: node_modules
    - run: echo ${{ secrets.customConfig }} > _secret.yml
    - run: npm install hexo-cli -g
    - run: npm install
    - run: npm run build --if-present
